# Generated by Django 3.0.7 on 2020-06-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profilePhoto',
            field=models.URLField(blank=True),
        ),
    ]
