# Generated by Django 3.0.7 on 2020-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_profilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='accountname',
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
