# Generated by Django 3.0.7 on 2020-06-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200613_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user',
            new_name='accountname',
        ),
    ]
