# Generated by Django 3.0.7 on 2020-06-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityName', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('lengthOfTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EntrustLaundryToWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washType', models.CharField(choices=[('1', 'damp washing'), ('2', 'dry cleaning')], max_length=1)),
                ('remark', models.CharField(max_length=100)),
                ('returnClothesTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpaceApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkingSpaceType', models.CharField(choices=[('1', 'Small car'), ('2', 'Heavy locomotive'), ('3', 'Scooter')], max_length=1)),
                ('desiredLocation', models.CharField(max_length=100)),
            ],
        ),
    ]
