# Generated by Django 3.0.7 on 2020-06-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceRequest', '0002_auto_20200614_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowfacility',
            name='lengthOfTime',
            field=models.DurationField(),
        ),
    ]
